metal3-io/cluster-api-provider-baremetal

pkg/cloud/baremetal/actuators/machine/actuator.go
This will panic as a Cluster may not exist, and won't exist in the
case of OpenShift.  Otherwise, this worked when I ran it against a
test cluster.  I was able to see these log messages as exepcted when I
created Machines.
=> actuator: Don't try to use non-existent Cluster.

Makefile, README.md
This target just simply compiles the two binaries just like the
Dockerfile does.  I left the rest of the existing Makefile, which was
based on the cluster-api provider developer docs for now.
=> Add "make build" and dev workflow instructions.

pkg/cloud/baremetal/actuators/machine/actuator.go
This actuator was based on docs in the upstream cluster-api gitbook.
This change syncs a change from those docs.
https://github.com/kubernetes-sigs/cluster-api/pull/750/files
=> Sync "Add directives for setting ClusterRole permissions"

cmd/manager/main.go
This patch syncs a change from the upstream cluster-api provider
implementation documentation.  See this PR for the change:
https://github.com/kubernetes-sigs/cluster-api/pull/780
and this issue for some more information about the problem it's
fixing:
https://github.com/kubernetes-sigs/cluster-api/issues/742
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> Add metrics-addr flag.

Makefile, config/rbac/rbac_role.yaml
A previous commit from PR #6 added directives in the code for setting
ClusterRole permissions.  This commit adds the corresponding necessary
change to the Makefile to act on those directives.
This corresponds to the following PR from cluster-api's provider
implementation documentation:
https://github.com/kubernetes-sigs/cluster-api/pull/779
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> Fix RBAC generation from the code.

Gopkg.lock, pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
I noticed that ReconcileMachineHealthCheck in the machine-api-operator uses
this approach when it puts a machine annotation on a Node. It seems worth using
the same approach for the host annotation.
=> uses k8s.io/client-go/tools/cache to generate host annotation value

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator.go:258:6: no new variables on left side of :=
=> actuator: Fix build error.

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
Previously if no host was available, the actuator would return an error. This
caused the controller to log an ugly stacktrace and retry every second, with a
gradual backoff to once every ~30 seconds.
With this change, there is no more stacktrace logged, and the retry interval is
fixed at 30s.
New log output:
```
2019/03/25 09:01:39 Checking if machine sample exists.
2019/03/25 09:01:39 Machine sample does not exist.
2019/03/25 09:01:39 Creating machine sample .
2019/03/25 09:01:39 No available host found. Requeuing.
```
Old log output:
```
2019/03/25 09:02:19 Checking if machine sample exists.
2019/03/25 09:02:19 Machine sample does not exist.
2019/03/25 09:02:19 Creating machine sample .
{"level":"error","ts":1553518939.1828089,"logger":"kubebuilder.controller","msg":"Reconciler …
```
=> gracefully requeues when no host is available

pkg/cloud/baremetal/actuators/machine/actuator.go
There's no point in provisioning to a host that is powered off.
=> set the host online when we provision it

Makefile, config/kustomization.yaml
The newest releases of kustomize block relative paths in the config.  This patch pulls in a fix to our vendored copy of cluster-api, and fixes our own config as well.
=> Fix compatibility with newer kustomize.

cmd/manager/main.go
Duplicate InitFlags and glog sync are not required
See https://github.com/kubernetes-sigs/cluster-api/pull/850#discussion_r268641086
=> cmd/manager: remove duplicate klog calls

pkg/cloud/baremetal/actuators/machine/actuator.go
In order to provision a worker node, we need to pass it the worker
user data secret.
=> set the user data for provisioning

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
A pointer bug caused the actuator to always choose the last host in the slice
of hosts, regardless of whether it was available or not.
The unit tests could have caught this bug, except that the test data happened
to be arranged such that the expected correct host to choose was always the
last one in the slice.
fixes #51
=> fixes bug that chose the same host every time

cmd/manager/main.go, pkg/cloud/baremetal/actuators/machine/actuator.go
This fixes a bug where the client caches the non-existence of a CRD, so if the
metalkube.org group doesn't exist when the controller starts, it will never
succeed at Listing or Getting BareMetalHosts.
Includes minor improvements to logging and error checking.
fixes #57
=> Waits for metalkube.org API group to be available before starting.

docs/dev/minikube.md
Due to 'vendor/sigs.k8s.io/cluster-api/config/crds/' is a folder, we must use '-k' flag instead of '-f' flag while adding CRDs from cluster-api. This PR intends to update the deployment guide to fix this error.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Fix error while adding CRDs from cluster-api

config/kustomization.yaml
This matches what the baremetal-operator uses by default, as well.
=> Use the metal3 namespace by default.

Makefile
Use the metal3 namespace for the components built from the cluster-api
repository, as well.
=> Use metal3 namepsace for cluster-api components.

pkg/cloud/baremetal/actuators/machine/actuator.go
This constant came from the sample provider implementation in
cluster-api docs.  It was missed when changing the sample to use
"baremetal" everywhere instead of the sample "solas" provider.
=> Fix ProviderName to be "baremetal".

config/rbac/rbac_role.yaml, pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/controller/add_machine.go
The cluster-api project has docs that describe how to build a
provider.  This patch syncs some recent changes to their documented
RBAC.
https://github.com/kubernetes-sigs/cluster-api/pull/947
=> Update RBAC from upstream docs.

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
This patch fixes a crash due to assuming that hardware details will
always be available on a BareMetalHost object.  A test case has been
added for this, as well.
Fixes #82.
=> Don't assume hardware details are available.

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
In order to ensure that fencing works correctly, we can't allow the
Machine object to be deleted while there is still a chance that the
BaremetalHost is still powered on and running. Delay successful
completion of the deletion until the actuator has verified that the Host
cannot be online.
Closes #84
=> Delay Machine deletion until BaremetalHost deprovisioned

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
We only want to update the image setting if the host does not already have
a consumer and image.
A consumer without an image is "externally provisioned" and assigning the
image will trigger reprovisioning. Since the control plane nodes will be
configured this way, reprovisioning will take them offline and try to turn
them into workers.
A host with an existing image is also already provisioned and upgrades are
not supported at this time. To re-provision ahost, we must fully deprovision
it and then provision it again.
Fixes #93
=> only set image and user data when we actually want to provision

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
If a Host is in an "externally provisioned" state, then we have no control over the Host's provisioning state. Therefore when deleting a Machine with an externally provisioned Host, we should wait only until
the Host has been powered off rather than for it to be deprovisioned (which will never happen).
=> Allow deletion of externally provisioned Hosts

pkg/cloud/baremetal/actuators/machine/actuator.go
The code already set the NodeHostname address type.  This patch sets
that same value as the NodeInternalDNS.
I ran into a component (openshift/cluster-machine-approver) that
expected a NodeInternalDNS field to be set on the Machine with the
hostname.
=> Set NodeInternalDNS address on Machine.

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
Externally provisioned hosts need the image as well, so always set it
unless it is already set.
=> ensure all hosts that are in use have an image reference

.travis.yml, Makefile, docs/dev/setup.md, tools/install_kustomize.sh
Generating manifests and running the test suite require kustomize and
kubebuilder.  Add a quick check for them to the Makefile to avoid less
obvious errors later if they are missing.
Closes issue #14.
=> Makefile: Add kubeubilder and kustomize checks.

.travis.yml, docs/dev/setup.md, tools/install_kustomize.sh
`go get` is broken.  The latest HEAD of kustomize needs go 1.12 or
later and uses `go install`.
=> Use binary for kustomize instead of `go get`

hack/Dockerfile.unit, hack/unit.sh, tools/install_kubebuilder.sh
Instead of installing kubebuilder and kustomize each time the unit
tests run in a container, just pre-install those in a container image.
Also update install_kubebuilder.sh to remove the downloaded tar.gz to
reduce the size of the resulting container image.
=> Create and use a unit test image.

hack/unit.sh
The script prevoiusly failed under prow because / was read-only.  There is an ARTIFACTS env var where cover.out can be placed.  This will also result in cover.out being stored as a job artifact for review.
=> Make the unit test script work under prow.

hack/govet.sh
When running under prow, running "go vet" was trying to write to
/.cache, which doesn't work.  Try setting an env var to move this
under /tmp.
=> hack/govet: Set XDG_CACHE_HOME

hack/unit.sh
This variable is set by prow.  When running this script manually, have
it default to /tmp.
=> hack/unit: Set a default value for ARTIFACTS

hack/Dockerfile.unit, hack/unit.sh
the current capbm-unit image has go version 1.11 . We need go 1.12
=> [v1alpha2] Change capbm-unit image to use golang image

hack/Dockerfile.unit, hack/unit.sh
Changing the path used to install kubebuilder and kustomize in capbm-unit image v1alpha2
=> Modify unit test image in v1alpha2 to avoid path collision in prow

Makefile, hack/Dockerfile.unit, hack/unit.sh
- change go build cache path to a writable folder
- copy kubebuilder execs in two location in capbm-unit image
- modify the unit tests script accordingly
=> [v1alpha2] Fix paths issue to run unit tests in v1alpha2 capbm-unit image

hack/Dockerfile.unit, hack/unit.sh
- a hack was added as long as the unit test job was broken, fixed now
- remove the creation of tmp dir in image due to permission issue
=> [v1alpha2] Remove v1alpha2 unit test hack and change tmp dir 

Makefile, README.md
now deploy examples by running for example
make deploy; make deploy-examples
The deployment of the CRDs and controllers is not included in the
examples anymore
=> [V1alpha2] Refactor the Makefile targets

Makefile, examples/generate.sh, hack/tools/install_kustomize.sh
CAPI has moved to v1alpha3 and will remove v1alpha2 types. We'll be using the branch release-0.2 before we move to v1alpha3.
Co-authored-by: Jan Tilles <jan.tilles@est.tech>
=> V1alpha2 Use CAPI release-0.2 branch to avoid v1alpha3 issues

Makefile
RBAC roles and bindings were not applied when running make install
=> [v1alpha2] Apply RBAC when running make install

baremetal/machine_manager.go
the providerID was metal3://<host.Name>. Modifying it to metal3.//<host.Namespace>/<host.Name>
=> [v1alpha2] Add namespace in providerID for unique naming

baremetal/cluster_manager.go, baremetal/machine_manager.go, controllers/baremetalmachine_controller.go
Kubeadmreset is not supported, will be part of CAPI control plane
management, and execBoostrap was a replacement for cloud-init in CAPD
=> Remove unneeded CAPD functions

baremetal/machine_manager.go, controllers/baremetalmachine_controller.go, controllers/baremetalmachine_controller_test.go, examples/metal3crds/metal3.io_baremetalhosts.yaml, examples/metal3plane/hosts.yaml, go.mod
- call update on machine after providerID change to ensure it is
called on change
- call update on machine when already provisioned to reflect
the update that triggered the reconcile
- add bmh in the machine controller tests
- add status to BMO fake CRs
=> various minor fixes

baremetal/machine_manager.go
ironic UID is not permanent, changing to bmh UID.
=> Use bmh node UID for providerID instead of ironic UID

baremetal/cluster_manager.go, baremetal/machine_manager.go
Currently, only a single error reason is hard coded. 
The caller need to provide both error message and error status.
=> Parameterize setting error reason on Machine and Cluster

controllers/baremetalcluster_controller_test.go, controllers/baremetalmachine_controller_test.go, controllers/suite_test.go, go.sum
This PR improves the assertions in BM Machine Controller tests by checking associated objects' spec and/or status.
* Fixes minor bugs in testcases
* Adds a test case 
* Minor refactoring of BM Cluster Controller test.
=> Improve assertions in BM Machine Contoller test

api/v1alpha2/baremetalcluster_types.go, baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go, baremetal/remote/remote.go, baremetal/remote/remote_test.go, controllers/baremetalcluster_controller_test.go, controllers/baremetalmachine_controller.go, controllers/baremetalmachine_controller_test.go, controllers/suite_test.go, go.mod, main.go
When no cloud provider is deployed, set the providerID by
directly interacting with the target cluster api.
=> Set node providerID on target cluster

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
If a Machine is being deleted and is associated with a BareMetalHost that has
no status, the deletion logic would fail to identify that the host is
unprovisioned. It would requeue forever, waiting for the host to reach an
unprovisioned state.
This can happen if there are BareMetalHosts without a running
baremetal-operator, and Machines with this provider running.
=> fixes stuck deletion when host has no Status

baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go
A host without status would block the deletion of the baremetal
machine, as it would default to waiting in the Delete function.
Now considering a host without status as deprovisioned during
the deletion of the baremetal machine
Similar to #195 for v1alpha2
=> [V1alpha2] Handle properly bmh state none while deleting baremetal machine

baremetal/baremetalcluster_manager_test.go, baremetal/baremetalmachine_manager_test.go, controllers/baremetalcluster_controller_integration_test.go, controllers/baremetalmachine_controller_integration_test.go, controllers/baremetalmachine_controller_test.go, controllers/suite_test.go
- improve the objects creation to avoid test pollution
- use assertion NotTo(HaveOccurred()) for errors instead of To(Succeed())
=> Minor fixes for the tests

pkg/cloud/baremetal/actuators/machine/actuator.go, pkg/cloud/baremetal/actuators/machine/actuator_test.go
This patch adds a couple of pieces of metadata to Machines to expose
some useful information as a label and an annotation.  Some generic
names are being used here to not be so tied to the details of the
BareMetalHost.
The instance-state annotation is set to the provisioning status of the
underlying BareMetalHost. The instance-type label is set to the
hardware profile of the underlying BareMetalHost.
Original PR was https://github.com/metal3-io/cluster-api-provider-baremetal/pull/104, opened this one against v1alpha1 instead once master moved to v1alpha2 dev.
=> Set instance-state and instance-type.

.travis.yml, hack/gofmt.sh, hack/govet.sh
This is a temporary workaround to have tests in place while prow is down
=> Add Tests in Travis while Prow cluster is down

Makefile, config/default/manager_image_patch.yaml
`make generate-examples` is now a dependency only for `make-deploy`. It needs to be run manually before `make deploy-bmo-cr` or if something is changed after deployment.
Also change temporarily the CAPBM image to use v1alpha3 tag.
=> ✨ Do not require generate-examples for Makefile targets

api/v1alpha3/baremetalcluster_types.go, api/v1alpha3/baremetalmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachinetemplates.yaml, examples/cluster/cluster.yaml, examples/controlplane/controlplane.yaml, examples/machinedeployment/machinedeployment.yaml
This was added unnecessarily to
BaremetalMachine, BaremetalCluster and BaremetalMachineTemplate
=> 🏃 Remove unneeded clusterName from external object CRDs

baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go
The clusterLabel deletion is fixed. Previously it was deleting all the labels. Now, it deletes the clusterLabel only. 
Co-authored-by: Mael Kimmerlin <mael.kimmerlin@est.tech>
=> :Bug: Fix clusterLabel deletion

controllers/baremetalcluster_controller.go, controllers/baremetalcluster_controller_integration_test.go, controllers/baremetalmachine_controller.go, controllers/baremetalmachine_controller_integration_test.go, controllers/baremetalmachine_controller_test.go, controllers/suite_test.go
This PR checks Cluster.Spec.Pause and cluster.x-k8s.io/paused Annotation in BareMetalCluster & BareMetalMachine reconcile.
Tests are added.
=> :Sparkles: Check Cluster.Spec.Pause and Pause Annotation in BMC & BMM reconcile

hack/Dockerfile.unit, hack/govet.sh
Required when adding the webhooks feature
/cc @kashifest 
/cc @fmuyassarov
=> 🏃 Update go version to 1.13 for unit test docker image

controllers/baremetalcluster_controller.go, controllers/baremetalmachine_controller.go
This PR adds the cluster name in the logs before checking if the object is paused. That gives more information for debugging
=> 🏃 Refactor logging for controllers

main.go
This PR allows to specify a namespace to watch for the controller. This allows to restrict the scope of the controller.
=> ✨ Add namespace selection for CAPBM controller

baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go
This PR adds ownerreferences and finalizers on the secrets that are created by CAPBM containing the userdata.
=> ✨ Add OwnerReference and Finalizer on created userdata secret

baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go
This PR adds an Ownerreference on the baremetalhost, set by CAPBM when selecting the baremetalhost. Clusterctl builds a tree of resources using the ownerreferences. the ownerreference is not directly used right now because we still have BMO installed out of the scope of clusterctl, but whenever that will not be the case anymore (i.e. we include BMO deployment in infrastructure-components.yaml) then this ownerreference is a must to ensure that the BMH gets moved along during the pivoting.
=> ✨ Set ownerreference on BareMetalHost

baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go, go.mod, go.sum
Currently, we always create a secret with the userdata for BMH. Since CABPK v1alpha3, CABPK creates a secret containing the userData. This PR removes the duplication of the secret where possible.
Several cases:
- no DataSecretName set, but Data is set in the Machine Bootstrap -> creates the secret
- DataSecretName set, but Machine and BMH are in different namespaces -> creates the secret, since the secret is referenced by name only in both cases, assuming that it is in the same namespace as the machine or as the BMH
- DataSecretName set and Machine and BMH in same namespace -> re-use CABPK secret
=> ✨ Modify the userdata secret creation logic

README.md, VERSIONING.md, baremetal/baremetalcluster_manager.go, baremetal/baremetalmachine_manager.go, baremetal/baremetalmachine_manager_test.go, baremetal/manager_factory.go, baremetal/manager_factory_test.go, config/default/kustomization.yaml, config/kustomization.yaml, controllers/baremetalcluster_controller.go, controllers/baremetalmachine_controller.go, docs/api.md, docs/deployment_workflow.md, docs/dev-setup.md, docs/getting-started.md, docs/testing.md, examples/provider-components/manager_tolerations_patch.yaml, hack/kind/start_controllers.sh, main.go
This is related to an issue in CAPI about renaming
Metal3.io provider from baremetal to metal3. It renames the provider from CAPBM to CAPM3. It is mostly cosmetic changes, except for the config/ folder that will modify the deployment (namespace and naming). No break in backwards compatibility.
**Which issue(s) this PR fixes**:
Fixes #267
=> ✨ Rename Provider from Baremetal to Metal3

main.go
This PR fixes the leader election configmap name
=> 🐛 Fix leader election configmap name
