metal3-io/cluster-api-provider-baremetal

pkg/cloud/baremetal/actuators/machine/actuator.go

Add a couple of TODO items as follow-ups to the discussion on PR #8.
Signed-off-by: Russell Bryant <rbryant@redhat.com>

actuator: Add a couple TODO items.

---

Gopkg.lock
pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go
vendor/github.com/evanphx/json-patch/.travis.yml
vendor/github.com/evanphx/json-patch/LICENSE
vendor/github.com/evanphx/json-patch/README.md
vendor/github.com/evanphx/json-patch/cmd/json-patch/file_flag.go
vendor/github.com/evanphx/json-patch/cmd/json-patch/main.go
vendor/github.com/evanphx/json-patch/merge.go
vendor/github.com/evanphx/json-patch/patch.go

Removes label creation on BareMetalHost and adds actuator unit tests

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

implements actuator Delete method

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

Also includes minor refactor improvements

Limits chooseHost to hosts in the machine's own namespace

---

pkg/cloud/baremetal/actuators/machine/actuator.go

uses BareMetalHost.Available method to determine if a host is available

---

pkg/cloud/baremetal/actuators/machine/actuator.go

Rather than hard-coding the image checksum, use the well-known URL
within the Ironic container to fetch it. This is still not ideal,
since we have to know where Ironic is, but it's better than updating
the hard-coded checksum value every time the image changes.

get the checksum of the image dynamically

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

Apparently this regressed at some point.

Saves a host when it's assigned a new MachineRef

---

cmd/manager/main.go

This should resolve `flag provided but not defined: -logtostderr` error when clusterapi start machine controller

Klog flags

---

pkg/cloud/baremetal/actuators/machine/actuator.go

After https://github.com/metalkube/baremetal-operator/pull/89 merges
the operator will support accepting a URL instead of a checksum value,
and we can skip downloading the checksum file content here and let
something further down the pipeline do that.
Fixes #40

pass the checksum url instead of the checksum to the baremetal operator

---

.travis.yml
tools/install_kubebuilder.sh

The bug that caused us to turn this off has been resolved.

enables unit test in CI

---

pkg/cloud/baremetal/actuators/machine/actuator.go
pkg/cloud/baremetal/actuators/machine/actuator_test.go

Eventually, this will add the node address(es) to the status of the
Machine object. For now, it's just an empty list.

Add node addresses to Machine status

---

cmd/manager/main.go

Add namespace command

---

hack/gofmt.sh
hack/govet.sh
hack/unit.sh

These scripts will make it easy to run each of these tests in the same
container that is used to run it in CI.

Add hack scripts to run tests in containers.

---

Makefile
controllers/baremetalcluster_controller.go
hack/Dockerfile.unit
hack/gofmt.sh
hack/govet.sh
hack/unit.sh

Broken scripts were copied, fixing the paths for v1alpha2

Fix go vet and go fmt paths

---

baremetal/machine_manager.go
config/rbac/role.yaml
controllers/baremetalmachine_controller.go

- Get annotations from BaremetalMachine instead of Machine for deletion
- Copy userdata from Machine into a secret referenced in
baremetalMachine and BaremetalHost

[v1alpha2] Fix deletion issue and add userdata secret creation for bmh

---

baremetal/cluster_manager.go
baremetal/machine_manager.go
baremetal/manager_factory.go
controllers/baremetalcluster_controller.go
controllers/baremetalmachine_controller.go
go.mod
go.sum

Use structured logs from controller-runtime and fix some linting issues

[v1alpha2] use controller-runtime logger and fix lint errors

---

Makefile

conflicts when using make run after make deploy

Remove rbac kustomization in install target

---

api/v1alpha2/baremetalcluster_types.go
baremetal/cluster_manager.go
config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
examples/cluster/cluster.yaml

Adds VIP in Baremetal Cluster manager
Co-authored-by: Xenwar <anwar.hassen@est.tech>
Signed-off-by: kashifest <kashif.khan@est.tech>

Add VIP in Baremetal Cluster

---

baremetal/machine_manager.go

The controller crashes on deletion of baremetalmachine objects

bug fix to prevent accessing Name on empty host

---

Makefile
config/default/manager_image_patch.yaml

move to quay.io image instead of keleustes

[v1alpha2] Use quay.io v1alpha2 image

---

controllers/baremetalcluster_controller_test.go
controllers/baremetalmachine_controller_test.go
controllers/suite_test.go

Co-authored-by: Kashif Khan <kashif.khan@est.tech>
This PR adds tests for BareMetalCluster reconciler

Add BareMetalCluster tests

---

baremetal/machine_manager.go
controllers/baremetalcluster_controller_test.go
controllers/baremetalmachine_controller_test.go
controllers/suite_test.go

Co-authored-by: Anwar Hassen <anwar.hassen@est.tech>
This PR adds BareMetalMachine Controller tests.

Add BareMetalMachine Controller tests 

---

Makefile
baremetal/machine_manager.go
controllers/baremetalmachine_controller.go
hack/gofmt.sh
hack/govet.sh
hack/markdownlint.sh
hack/shellcheck.sh
hack/unit.sh

Wait for the baremetalhost to be provisioned before setting
the providerID and ready flag on the baremetalmachine

[V1alpha2] Modify baremetalmachine workflow

---

controllers/baremetalcluster_controller_test.go
controllers/baremetalmachine_controller_test.go
controllers/suite_test.go

Refactor unit tests for controller folder

---

Makefile
baremetal/machine_manager.go
go.mod

- v1alpha2 changes
- lint fixes
- unit tests will follow in a separate comit

CAPBM machine manager updates

---

controllers/baremetalcluster_controller.go
controllers/baremetalcluster_controller_test.go
controllers/baremetalmachine_controller_test.go

- wait for all machine descendants from the cluster owning the baremetalcluster to be deleted before deleting the baremetalcluster
- fix typo in controller tests

V1alpha2 fix deletion workflow for cluster

---

baremetal/machine_manager.go

fix GetProviderID function

---

baremetal/machine_manager_test.go

Note,
https://github.com/metal3-io/cluster-api-provider-baremetal/pull/155
needs to be merged before this commit

CAPBM machine mgr unit test

---

controllers/baremetalcluster_controller_test.go

This PR makes small improvement of the BM cluster controller test by adding assertions on the type of error and re-queue duration.

Add assertions to BM cluster controller test

---

controllers/baremetalcluster_controller.go
controllers/baremetalcluster_controller_test.go
controllers/baremetalmachine_controller.go

Set error reason and message on Status of BMCluster and BMMachine resources.
Co-authored-by: Anwar Hassen <anwar.hassen@est.tech>

Set erroreason & errormsg in BMCluster & BMMachine

---

baremetal/cluster_manager.go
baremetal/machine_manager.go
controllers/baremetalcluster_controller.go
controllers/baremetalmachine_controller.go
controllers/baremetalmachine_controller_test.go

Sets and Verifies BMMachine Error status

Sync and verify error status and message on BMMachine object

---

api/v1alpha2/baremetalcluster_types.go
api/v1alpha2/baremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml

Addes shortnames for:
baremetalCluster - bmc;bmcluster 
baremetalMachine- bmm;bmmachine

Add shortNames for baremetalCluster and baremetalMachine

---

api/v1alpha2/baremetalcluster_types.go
api/v1alpha2/baremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_baremetalmachines.yaml

Added print infos:
Baremetalcluster: Ready, Error, APIEndpoints
Baremetalmachine: Phase, Error

Extent kubectl printout for baremetalcluster and baremetalmachine

---

baremetal/baremetalmachine_manager_test.go

fix BMM flaky TestAssociate unit test

---

controllers/baremetalcluster_controller_test.go

Make the testing framework uniform across the repository
Based on #190

[V1alpha2] Refactor Baremetal cluster controller tests to use Ginkgo

---

controllers/baremetalmachine_controller_test.go

Make the testing framework uniform across the repository

[V1alpha2] Refactor Baremetal machine controller tests to use Ginkgo

---

baremetal/requeue_error_test.go
baremetal/suite_test.go

use ginkgo and gomega to uniformize the tests

Refactor the error tests for the managers

---

baremetal/baremetalcluster_manager_test.go
controllers/baremetalcluster_controller_test.go

[V1alpha2] Refactoring baremetal cluster manager tests

---

baremetal/baremetalmachine_manager.go
baremetal/baremetalmachine_manager_test.go

Refactor baremetal machine manager tests

---

config/default/manager_image_patch.yaml
hack/unit.sh

Change image tag to master

---

config/default/manager_image_patch.yaml
hack/unit.sh

switch to v1alpha1 for capbm image tag

Fix image version for deployment

---

.travis.yml
hack/gofmt.sh
hack/govet.sh
hack/markdownlint.sh
hack/shellcheck.sh
hack/unit.sh

This is a temporary workaround to have tests in place while prow is down

Add Tests in Travis while Prow cluster is down (v1alpha2)

---

README.md

/cc @fmuyassarov 
/cc @kashifest

add E2E tests status for v1alpha2

---

README.md

add E2E tests build status for v1alpha1

---

CONTRIBUTING.md
VERSIONING.md

adds CONTRIBUTING.md and VERSIONING.md

📖 Add developer documentation regarding version and releases

---

config/default/manager_image_patch.yaml

V1alpha3 development is happening in master from now on

🐛 Fix manager image in release 0.2 branch

---

baremetal/baremetalmachine_manager.go
baremetal/baremetalmachine_manager_test.go

When the secret comes from CAPI, the key is "value" while
BMO expects the key "userData". Adding the secret creation based
on the CABPK secret content

🐛 Fix secret handling for baremetalmachine

---

baremetal/baremetalmachine_manager.go
baremetal/baremetalmachine_manager_test.go

The userdata coming from CABPK does not need decryption

🐛 Fix base64 decoding for UserData secret

---

Makefile
hack/tools/release/notes.go
hack/tools/tools.go

/cc @kashifest 
/cc @jan-est 
/cc @fmuyassarov

📖 Add release notes tool from Cluster API project

---

baremetal/baremetalmachine_manager.go
baremetal/baremetalmachine_manager_test.go

This PR adds "cluster.x-k8s.io/cluster-name" label to BMH and BMC credential secret. 
Test functions for this is also added.

:sparkles: Add clusterLabel in BMH and BMC secret + tests

---

config/default/manager_image_patch.yaml

This is to follow the change of development branch

🏃 Change manager image to master from v1alpha3

---

config/default/manager_image_patch.yaml

🏃 bump image to v0.2.1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
hack/markdownlint.sh

for pull requests and issues.
/cc @kashifest 
/cc @jan-est 
/cc @fmuyassarov

🏃 Add Github templates

---

.gitignore
Makefile
docs/getting-started.md
examples/generate.sh
examples/provider-components/kustomization.yaml
metadata.yaml

This PR adds the missing pieces to fulfill the clusterctl contract. It adds documentation, the metadata.yaml file and renames the components files to follow the new naming conventions.

✨ Add getting-started.md, metadata.yaml and update generate.sh

---

.gitignore
.mdlrc
Makefile
clusterctl-settings.json
examples/cluster/cluster.yaml
examples/clusterctl-templates/clusterctl-cluster.yaml
examples/clusterctl-templates/example_variables.rc
examples/controlplane/controlplane.yaml
go.mod
go.sum

This PR adds a cluster template and the needed documentation. It also adds a CACPK example and modifies the makefile to include the proper files in the release.

✨ Adding clusterctl cluster template

---

.mdlrc
Makefile
README.md
docs/api.md
docs/deployment_workflow.md
docs/dev-setup.md
docs/releasing.md

This PR updates the documentation for v1alpha3 and adds the releasing guidelines as started by @Arvinderpal in https://github.com/metal3-io/cluster-api-provider-baremetal/pull/226 (inactive)

📖 Update the documentation for v1alpha3

---

README.md

This is primarily just an excuse to test CI, but is based on these
guidelines:
https://github.com/metal3-io/metal3-docs/blob/master/design/bare-metal-style-guide.md

Change Baremetal to Bare Metal
